# Generated by Django 2.2 on 2020-06-18 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_indicator_livedata_state_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='sysTime',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
