# Generated by Django 3.0.7 on 2020-06-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('interval', models.IntegerField()),
                ('interval_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('percent', models.IntegerField()),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accuracy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accuracylevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'accuracylevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accuracystate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
            options={
                'db_table': 'accuracystate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activitylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('hour', models.TimeField()),
                ('type', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activitylog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actychoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'actychoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actysubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'actysubtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'actytype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('interval', models.IntegerField()),
                ('interval_unit', models.CharField(blank=True, max_length=5, null=True)),
                ('value', models.IntegerField()),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forecast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forecastlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'forecastlevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forecaststate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
            ],
            options={
                'db_table': 'forecaststate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('value', models.IntegerField()),
                ('num_events', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'glucose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('glucose', models.IntegerField()),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'livedata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Livestate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'livestate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField()),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommended',
                'managed': False,
            },
        ),
    ]
