# Generated by Django 3.0.7 on 2020-08-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200817_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='source',
            field=models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.CASCADE, to='webapp.Source'),
        ),
    ]
